services:
  app-client:
    build:
      context: . # Build the Dockerfile from the current directory
      dockerfile: Dockerfile
      target: dev # Use the 'dev' stage of the multistage Dockerfile
    image: report-agent-client
    container_name: report-agent-client-container
    ports:
      - "3000:3000" # Ensure PORT is set in your environment
    environment:
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    command: ["npm", "run", "dev"] # Run the app in development mode
    volumes:
      - .:/app # Bind mount allows live code updates during development
      - /app/node_modules
